
[functions.fetch-woocommerce-data]
enabled = true
verify_jwt = true
import_map = "./functions/fetch-woocommerce-data/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/fetch-woocommerce-data/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/fetch-woocommerce-data/*.html" ]

[functions.fetch-asana-data]
enabled = true
verify_jwt = true
import_map = "./functions/fetch-asana-data/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/fetch-asana-data/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/fetch-asana-data/*.html" ]

[functions.fetch-google-ads-data]
enabled = true
verify_jwt = true
import_map = "./functions/fetch-google-ads-data/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/fetch-google-ads-data/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/fetch-google-ads-data/*.html" ]
